"""
Stream handling for LLM responses.

Extracts streaming, metrics tracking, and cost calculation into a
reusable class shared by all agents.
"""

from collections.abc import Callable
from dataclasses import dataclass, field

from packages.core.llm_client import LLMClient, TokenUsage
from packages.core.pricing import ModelPricing, calculate_cost_from_litellm
from packages.telemetry.metrics import MetricsTracker, ResponseMetrics

_MAX_AGENTIC_ITERATIONS = 5


@dataclass
class StreamResult:
    """Result of a streamed LLM response."""
    text: str
    usage: TokenUsage
    cost_usd: float
    metrics: ResponseMetrics
    tool_messages: list[dict] = field(default_factory=list)


class StreamHandler:
    """Streams LLM responses while tracking metrics and cost."""

    def __init__(
        self,
        client: LLMClient,
        metrics_tracker: MetricsTracker,
        pricing: ModelPricing | None,
        model_id: str,
        on_tool_call: Callable[[str], None] | None = None,
        on_chunk: Callable[[str], None] | None = None,
    ):
        self.client = client
        self.metrics_tracker = metrics_tracker
        self.pricing = pricing
        self.model_id = model_id
        self.on_tool_call = on_tool_call
        self.on_chunk = on_chunk

    def stream(
        self,
        messages: list[dict],
        print_chunks: bool = False,
        tool_registry=None,
    ) -> StreamResult:
        """Stream an LLM response, tracking metrics and cost.

        When tool_registry is provided and non-empty, runs an agentic loop:
        intermediate non-streaming calls handle tool invocations, then the
        final answer is streamed as usual.

        Args:
            messages: Messages to send to the LLM.
            print_chunks: Whether to print chunks to stdout as they arrive.
            tool_registry: Optional ToolRegistry. None or empty → simple path.

        Returns:
            StreamResult with full text, usage, cost, and metrics.
        """
        # Import here to avoid circular imports at module load time
        from packages.core.tools.base import ToolRegistry
        from packages.core.tools.executor import execute_tool_calls

        tools_format = None
        if tool_registry is not None and not tool_registry.is_empty():
            messages, tools_format = self._run_agentic_loop(messages, tool_registry, execute_tool_calls)

        return self._stream_simple(messages, print_chunks, tools=tools_format)

    def _run_agentic_loop(self, messages: list[dict], tool_registry, execute_tool_calls) -> tuple[list[dict], list[dict]]:
        """Run agentic tool-calling loop. Returns (messages, tools_format) for final streaming."""
        tools_format = tool_registry.to_litellm_format()
        accumulated_usage = TokenUsage()
        tool_messages: list[dict] = []

        for _ in range(_MAX_AGENTIC_ITERATIONS):
            response = self.client.complete(messages, tools=tools_format)
            choice = response.choices[0]

            if choice.finish_reason != "tool_calls":
                break

            # Only accumulate "tool_calls" responses (these won't be regenerated by streaming)
            if hasattr(response, "usage") and response.usage:
                accumulated_usage = TokenUsage(
                    prompt_tokens=accumulated_usage.prompt_tokens + (response.usage.prompt_tokens or 0),
                    completion_tokens=accumulated_usage.completion_tokens + (response.usage.completion_tokens or 0),
                    total_tokens=accumulated_usage.total_tokens + (response.usage.total_tokens or 0),
                )

            # UX feedback for each tool call
            for call in choice.message.tool_calls:
                if self.on_tool_call is not None:
                    self.on_tool_call(call.function.name)
                else:
                    print(f"[Tool: {call.function.name}]")

            # Execute tool calls and append results
            assistant_msg = choice.message.model_dump() if hasattr(choice.message, "model_dump") else dict(choice.message)
            tool_results = execute_tool_calls(choice.message.tool_calls, tool_registry)
            messages = [*messages, assistant_msg, *tool_results]

            # Track tool messages for history persistence
            tool_messages.append(assistant_msg)
            tool_messages.extend(tool_results)

        # Store accumulated intermediate usage so _stream_simple can add to it
        self._intermediate_usage = accumulated_usage
        self._tool_messages = tool_messages
        return messages, tools_format

    def _stream_simple(self, messages: list[dict], print_chunks: bool, tools: list[dict] | None = None) -> StreamResult:
        """Stream the final response and return a StreamResult."""
        self.metrics_tracker.start_request()
        response = self.client.chat_stream(messages, tools=tools)

        chunks: list[str] = []
        first_token = True
        for chunk in response:
            if first_token:
                self.metrics_tracker.record_first_token()
                first_token = False
            if self.on_chunk is not None:
                self.on_chunk(chunk)
            elif print_chunks:
                print(chunk, end="", flush=True)
            chunks.append(chunk)

        usage = response.usage

        # Add any accumulated intermediate usage
        intermediate = getattr(self, "_intermediate_usage", None)
        if intermediate is not None:
            usage = TokenUsage(
                prompt_tokens=usage.prompt_tokens + intermediate.prompt_tokens,
                completion_tokens=usage.completion_tokens + intermediate.completion_tokens,
                total_tokens=usage.total_tokens + intermediate.total_tokens,
            )
            self._intermediate_usage = None

        cost_usd = 0.0
        if self.pricing:
            cost_usd = self.pricing.calculate_cost(usage.prompt_tokens, usage.completion_tokens)
        else:
            cost_usd = calculate_cost_from_litellm(response.raw_response)

        response_metrics = self.metrics_tracker.finish_request(
            prompt_tokens=usage.prompt_tokens,
            completion_tokens=usage.completion_tokens,
            cost_usd=cost_usd,
            model=self.model_id,
        )

        # Collect any tool messages from the agentic loop
        tool_messages = getattr(self, "_tool_messages", [])
        self._tool_messages = []

        return StreamResult(
            text="".join(chunks),
            usage=usage,
            cost_usd=cost_usd,
            metrics=response_metrics,
            tool_messages=tool_messages,
        )
