"""
Generate data/codebase_map.md — a compact project summary for the developer agent.

Scans the project tree for:
- Module structure with docstrings
- All registered agents (name, command, description)
- All tool modules (name, description)
- Config structure summary

Usage:
    uv run python scripts/generate_codebase_map.py
"""

import ast
from pathlib import Path

import yaml


def get_project_root() -> Path:
    return Path(__file__).parent.parent


def get_module_docstring(filepath: Path) -> str:
    """Extract the module-level docstring from a Python file."""
    try:
        tree = ast.parse(filepath.read_text(encoding="utf-8"))
        docstring = ast.get_docstring(tree)
        if docstring:
            # Return first line only
            return docstring.strip().split("\n")[0]
    except (SyntaxError, UnicodeDecodeError):
        pass
    return ""


def scan_modules(root: Path) -> list[str]:
    """Scan Python packages and return module descriptions."""
    lines: list[str] = []
    packages = [
        "packages/core",
        "packages/agents",
        "packages/integrations",
        "packages/skills",
        "packages/telemetry",
        "apps/cli",
    ]

    for pkg in packages:
        pkg_path = root / pkg
        if not pkg_path.is_dir():
            continue
        lines.append(f"\n### `{pkg}/`\n")

        py_files = sorted(pkg_path.glob("*.py"))
        for f in py_files:
            if f.name == "__init__.py":
                continue
            doc = get_module_docstring(f)
            rel = f.relative_to(root)
            if doc:
                lines.append(f"- `{rel}` — {doc}")
            else:
                lines.append(f"- `{rel}`")

    return lines


def scan_agents(root: Path) -> list[str]:
    """Scan agent directories for meta.yaml or AGENT_META."""
    lines: list[str] = ["\n## Agents\n"]
    agents_dir = root / "packages" / "agents"

    for child in sorted(agents_dir.iterdir()):
        if not child.is_dir() or child.name.startswith("_") or child.name == "__pycache__":
            continue

        meta_file = child / "meta.yaml"
        if meta_file.is_file():
            try:
                with open(meta_file) as f:
                    meta = yaml.safe_load(f) or {}
                name = meta.get("name", child.name)
                cmd = meta.get("command", f"/{name}")
                desc = meta.get("description", "")
                lines.append(f"- **{name}** (`{cmd}`) — {desc} [data-driven]")
                continue
            except Exception:
                pass

        init_file = child / "__init__.py"
        if init_file.is_file():
            lines.append(f"- **{child.name}** — (python-class agent)")

    return lines


def scan_tools(root: Path) -> list[str]:
    """Scan tool modules."""
    lines: list[str] = ["\n## Tools\n"]
    tools_dir = root / "packages" / "core" / "tools"

    for f in sorted(tools_dir.glob("*.py")):
        if f.name in ("__init__.py", "base.py", "executor.py"):
            continue
        doc = get_module_docstring(f)
        rel = f.relative_to(root)
        if doc:
            lines.append(f"- `{rel}` — {doc}")
        else:
            lines.append(f"- `{rel}`")

    return lines


def scan_config(root: Path) -> list[str]:
    """Summarize config structure."""
    lines: list[str] = ["\n## Config Structure (`config/default.yaml`)\n"]
    config_path = root / "config" / "default.yaml"

    if not config_path.is_file():
        lines.append("Config file not found.")
        return lines

    try:
        with open(config_path) as f:
            config = yaml.safe_load(f) or {}
        for key in config:
            if key.startswith("_"):
                continue
            val = config[key]
            if isinstance(val, dict):
                subkeys = ", ".join(val.keys())
                lines.append(f"- `{key}:` — {{{subkeys}}}")
            else:
                lines.append(f"- `{key}:` {val}")
    except Exception as e:
        lines.append(f"Error reading config: {e}")

    return lines


def main():
    root = get_project_root()
    output_path = root / "data" / "codebase_map.md"

    sections: list[str] = []
    sections.append("# JARVIS Codebase Map\n")
    sections.append("*Auto-generated by `scripts/generate_codebase_map.py`*\n")

    sections.append("\n## Module Structure\n")
    sections.extend(scan_modules(root))
    sections.extend(scan_agents(root))
    sections.extend(scan_tools(root))
    sections.extend(scan_config(root))

    content = "\n".join(sections) + "\n"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"Generated: {output_path.relative_to(root)} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
